### PR TITLE
added three sketches from P_2_0

### PR DESCRIPTION
**Pull request by lew-code**

### CODE REVIEW

**Comment by b-g** [comment]
@lew-code Thanks! But the PR has 0 changed files ... please double check and try again.

**Comment by lew-code** [comment]
whoops, forgot to commit :)

**Comment by b-g** [comment]
Thanks for this!! Please pull, then change the path and name of the gd lib ... I changed/refactored it on Monday. Best, B

**Comment by b-g** [comment]
Hi @lew-code, so are we good? Please write in future after you adjust a PR a quick comment ... so that I'm notified and now that we can go ahead. Cheers! B

**Comment by lew-code** [comment]
roger that :)

**Comment by b-g** [comment]
Merged via https://github.com/generative-design/Code-Package-p5.js/commit/68372086fa7f90e9fbde83d30085dc3e87e6a655 ... please make sure not to "mix" pull requests ... otherwise this will become a git nightmare for me :)

**Pull request closed without merging**
