### PR TITLE
Added P_2_1_3_04

### PR DESCRIPTION
**Pull request by Niels-NTG**
Port of `P_2_1_3_04.pde`.

I haven't managed to exactly port over drawMode 2. p5 doesn't seem to support `fill(Color, alphaValue)`

### CODE REVIEW

**Comment by b-g** [comment]
@Niels-NTG 

Many thanks for all this!!

RE: `fill(Color, alphaValue)`
it does kind of ... write instead fill(grey, grey, grey, alpha)

Will take some time to merge the PR ... yesterday my son was born 👶! :) Be patient with me.

All the best,
B

**Comment by Niels-NTG** [comment]
Congratulations!

**Comment by Niels-NTG** [comment]
I fixed the problem by using RGB colormode for the whole sketch.

**Comment by b-g** [comment]
@Niels-NTG Many thanks!

**Pull request merged**
