### PR TITLE
Added P_3_1_3_01

### PR DESCRIPTION
**Pull request by Niels-NTG**
Port of `P_3_1_3_01.pde`

### CODE REVIEW

**Comment by b-g** [comment]
@Niels-NTG Thanks! But looks quite bit different in comparison to the processing sketch (alpha of the letters etc.). Please tweak it a bit further.

**Comment by Niels-NTG** [comment]
After some long overdue investigation I figured out that this sketch and its peers `P_3_1_3_02` ( #59 ), `P_3_1_3_03` ( #60 ) and `P_3_1_3_04` ( #61 ) render incorrectly with Chrome. The browser I've used to test pretty much all sketches up to now. For some reason the aforementioned sketches do render correctly in Firefox, in addition to running significantly smoother. See below for a comparison of the Processing 3 version alongside the Chrome and Firefox versions.

schermafbeelding 2016-04-03 om 13 48 37

Not sure how to fix this. Seems like there are some inconsistencies in how different browsers draw the canvas. For example, having worked on other p5 projects I've noticed that Safari draws lines with a strokeWidth of less than 1 without any anti-aliasing, resulting in ugly pixelly hard jagged lines. While Chrome renders these lines just fine.

**Comment by b-g** [comment]
Fixed! No browser inconsistency ... simply a join array bug, see https://github.com/generative-design/Code-Package-p5.js/commit/becc1ed6f6cc532fcca4a26f74e37d0870c5ad8e some of the text was doubled in an odd way.

**Comment by b-g** [comment]
In my chrome:
screen shot 2016-07-06 at 15 41 59

**Comment by Niels-NTG** [comment]
Oops… Guess I confused p5's own version of [`join()`](http://p5js.org/reference/#/p5/join) that's similar to the Java/Processing version, with the standard JavaScript one.

**Pull request merged**
