### PR TITLE
Added P_1_2_3_03 sketch

### PR DESCRIPTION
**Pull request by pbogdan03**
Tried to use lerpColor() to fake a gradient, but I've seen that there's a problem with colorMode(HSB) and that you've already submitted an issue, so I'll check in on that.

### CODE REVIEW

**Comment by b-g** [comment]
Hi @pbogdan03,

Many thanks for this! However did you try it with the [WEBGL mode](https://github.com/processing/p5.js/wiki/Getting-started-with-WebGL-in-p5)? Not to have the gradients would be really a pity!

Hence we should try harder! :) Can you please investigate in the [p5.js forum](http://forum.processing.org/two/categories/p5-js-programming-questions) what the equivalent of the following code from processing 2.0 is?

```java
void setup() {
  size(128, 128, OPENGL);
  background(128);
  noStroke();
  beginShape();
  fill(0);
  vertex(30, 20);
  vertex(85, 20);
  fill(0,255,0);
  vertex(85, 75);
  vertex(30, 75);
  endShape();
}
``` 

Output should be:
screen shot 2015-10-27 at 11 02 18

Also, please pull and change
* the path and name of the gd lib 
* add the 'save color palette' feature

Cheers!
B

**Comment by pbogdan03** [comment]
Hello @b-g,
WebGL doesn't seem to work at all, even in a new sketch, can't figure it out... and the forum doesn't seem to exist anymore :)), will check it out tomorrow, but still didn't figure out the gradient, still looking into it

Bogdan

**Comment by b-g** [comment]
Hi @pbogdan03, any news on the WEBGL end? :) Best, B

**Comment by pbogdan03** [comment]
Hey @b-g, the WEBGL renderer seems to have a problem with beginShape() in that is only renders the first three vertices, I'll submit an issue with that. Moreover, the gradient fill isn't working anyway, but I've seen that there's a pull request on the p5 development with HSB support for lerpColor(), so I think that's the way to go for now :)

**Comment by b-g** [comment]
Hi @pbogdan03 any news? It seems lerpColor() is fixed ... https://github.com/processing/p5.js/issues/1029#event-458292433 ... but I believe this won't help us for the beginShape() issue.

**Comment by pbogdan03** [comment]
Hello, I don't have any news beginShape() issue, it is still behaving differently than Processing, in that it doesn't accept different fill colors on the same shape. Maybe I'll try to fake a gradient using lerpColor() with HSB, is that ok or do you want to keep using beginShape()?

**Comment by b-g** [comment]
Are you still on it? Still alive? :) As there seems to be no quick fix to this ... please write a custom gradient(x,y,w,h,c1,c2) function. so that we have a interim solution. ok?

**Comment by b-g** [comment]
... and let me add ... just get a reference to canvas and use http://www.w3schools.com/tags/canvas_createlineargradient.asp for the gradient(x,y,w,h,c1,c2) function.

**Comment by pbogdan03** [comment]
Sorry for the delay, I can't seem to find any free time to work on this, been caught up with work. Maybe I'll manage to do something in the weekend. 
Cheers!

**Comment by b-g** [comment]
@pbogdan03 I guess you are out? :(

**Pull request closed without merging**
