### PR TITLE
code cleanup and syntax updating

### PR DESCRIPTION
**Pull request by joeyklee**
Code cleanup and syntax updates:
1. assign arrays to global variables in setup.
2. changed “gird” to “grid” for consistency in one sketch
3. changed circleAlpha value from 0-1 scale to 0-255 scale
4. updated color retrieval functions ==> hue(), lightness(), saturation()

### CODE REVIEW

**Comment by b-g** [comment]
@joeyklee Many thanks! Just: P_2_1_1_03 hotkeys are just working partly, compare with P_2_1_1_03.pde

**Comment by joeyklee** [comment]
@b-g hotkeys for P_2_1_1_03 should be working properly now :)

**Comment by b-g** [comment]
@joeyklee Thanks + close! But `M_1_4_01` needs more love:
* no preview image in folder
* remove all things related to 'p' (high res export via tilesaver)
* prevent default right click event
* remove timestamp function

**Comment by joeyklee** [comment]
@b-g I'm having issues with the png export.. could it be the webgl renderer?

**Comment by b-g** [comment]
@joeyklee Thanks + merged with #125.

**Pull request closed without merging**
