### PR TITLE
Added P_2_2_1_01

### PR DESCRIPTION
**Pull request by Niels-NTG**
Port of `P_2_2_1_01.pde`

The capitalised static variables of Java don't really fit with JS. So I replaced them with a single array of strings like so `var directions = ["NORTH", "NORTHEAST", "EAST", "SOUTHEAST", "SOUTH", "SOUTHWEST", "WEST", "NORTHWEST"];`

### CODE REVIEW

**Comment by b-g** [comment]
@Niels-NTG Many thanks! But I have to say I like the old version (w/o the directions array) better, as it is easier to get. I don't think that it is a problem for our audience to have a capitalised variable name in javascript. Can I have a version in the style of the old code?

**Comment by Niels-NTG** [comment]
Yea, guess you're right. I will change it.

**Comment by Niels-NTG** [comment]
Ok, just changed the directions to how they where implemented in the original Processing version.

**Comment by b-g** [comment]
@Niels-NTG Many thanks!! Merged!

**Pull request merged**
