### PR TITLE
Added P_2_2_5_02

### PR DESCRIPTION
**Pull request by Niels-NTG**
Port of `P_2_2_5_02.pde`

I have some ideas on how to improve this particular sketch. Currently only 2 of the 11 svg files are used in the sketch. It might be fun to have a key that randomly picks a set of two SVG's from an array of SVG files.

### CODE REVIEW

**Comment by b-g** [comment]
Sure, but please make sure that it reproduces the old behaviour ... But the bigger picture with SVG is for me, that currently in p5js a SVG just becomes an pixel image and it becomes no longer ad-hoc modifiable like as it is in processing e.g. you can't change the fill color dynamically. A lot of the SVG as modul idea relies an this feature. Not sure how to deal with it.

**Comment by Niels-NTG** [comment]
The Processing Foundation and collaborators are [actively working](https://github.com/processing/p5.js/issues/458) on full SVG support. [Zeno Zeng](https://github.com/zenozeng) from the Processing Foundation currently has [a library for p5](https://github.com/zenozeng/p5.js-svg) that adds SVG support. I think they intend to eventually merge with p5.

**Comment by Niels-NTG** [comment]
Until then I will just keep the sketch as it currently is. We can re-evaluate it at a later point.

**Comment by b-g** [comment]
👍! Good to know!

**Comment by b-g** [comment]
@Niels-NTG Thanks! 👍

**Pull request merged**
