### PR TITLE
Added P_4_3_1_01

### PR DESCRIPTION
**Pull request by Niels-NTG**
Port of `P_4_3_1_01.pde`

### CODE REVIEW

**Comment by b-g** [comment]
@Niels-NTG Hope your'e doing great! Many thanks for new PR!! It will take me some time to review it (as usual, sorry!) ... I'm at paternity leave for the next 3.5 weeks. But I'm planning to work with more energy on all this in August. Stay tuned! Best, Benedikt

**Comment by Niels-NTG** [comment]
@b-g I'm doing great. Just started a job as a front end developer! No worries. While you're away I will attempt to continue the work on the project if the current state of the p5 library allows for it.

**Comment by b-g** [comment]
@Niels-NTG Thanks!! Btw I've updated to the newest p5 version ... + A good start with the new job!

**Comment by b-g** [comment]
@Niels-NTG many thanks + merged!

**Pull request merged**
